### ISSUE TITLE
[Epic] MVP launch

### ISSUE THREAD

**Issue by jacobheun** [code4rena-dev/botrace-utils#1]
## Summary
The botrace-utils library has 2 primary purposes for launch:
1. Allow Bot Race crews to install a binary via npm that allows them to validate their JSON file submissions, and generate markdown from their submission the same way we generate it for Github. This will give crews the ability to test updates to their bots outside of very tight bot race windows.
2. Replace the existing validation and markdown generation that is done in API v0 today. This will also ensure that if we want/need to perform the same actions in other places, such as the website, we can do so from the same source of truth.

### Library usage - API v0
- [x] Replicate existing api v0 bot race markdown rendering functionality so that this library can be used in its place
- [x] Replicate existing api v0 bot race schema validation so that this library can be used in its place
- [x] [Update api v0](https://github.com/code4rena-dev/api.code4rena.com/pull/1402) to use this library for markdown rendering and schema validation

### CLI Tool for Bot Racers
- [x] Add a command that takes a Bot Report json file and generates markdown exactly as it's generated for github
  - Run the report through validation, by default, before rendering the markdown
- [x] Add a command to validate a Bot Report json file against a schema
  - Allow for specifying the schema version, default to latest

## Security Considerations
- The biggest potential area for a vulnerability in this code base is going to be in the markdown generation. Binary usage is less of a concern as the primary user of this will be bot racers rendering their own json. However, as we intend to render the markdown via the same internal library logic, we need to ensure that user submitted json is being properly escaped during markdown generation.
- The other potential avenue is during JSON schema validation, which will be done by the ajv library. Both this and markdown generation should include a suite of tests to verify protection for common attacks.

### Planned External Libraries
- For markdown generation we are planning to just use JS template literals to avoid an external library for generation.
- JSON schema validation is currently done in api v0 via https://www.npmjs.com/package/ajv, we plan to continue to use that in this library at this time.
